site_name: 30 days of Pandas!
site_author: '@dyadyajora'
site_description: Notes for 30 days of Pandas leetcode challange.
site_url: https://pandas-challenge.jora.dev/
repo_name: dyadyajora/pandas_challenge
repo_url: https://github.com/dyadyajora/pandas_challenge
edit_uri: ""
theme:
  palette:
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  name: material
  favicon: img/favicon.png
  logo: img/logo.svg
  features:
    - navigation.footer
use_directory_urls: false
nav:
  - Home: index.md
  - Notes: notes.md
  - About: about.md
plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ru
          name: Русский
          build: true
          nav_translations:
            Home: Главная
            Notes: Заметки
            About: Инфо
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details