name: Build mkdocs site and upload to S3 - develop version

on:
  push:
    branches:
    - "master"
    - "**/**"
  pull_request:
    branches:
      - "master"

env:
  AWS_REGION : "us-east-1"
  AWS_REGION_LAB: "us-east-1"

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download source
      uses: actions/checkout@v3
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true
      name: Fetch git tags
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Build site
      run: mkdocs build
    - name: Setup versions in env variables
      id: version
      run: |
        function version { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }
        echo "THIS_VERSION=$(cat version | sed s/^v//)" >> $GITHUB_ENV
        echo "THIS_VERSION_COMPARABLE=$(version $(cat version | sed s/^v//))" >> $GITHUB_ENV
        echo "LATEST_VERSION_COMPARABLE=$(version $(git describe --tags $(git rev-list --tags --max-count=1) | sed s/^v// 2> /dev/null || echo '0'))" >> $GITHUB_ENV
        echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}"  >> $GITHUB_ENV
    - name: configure LAB AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ASSUME_ROLE_LAB }}
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_REGION_LAB }}
    - name:  Copy to LAB S3
      run: |
        aws s3 sync ./site/ s3://${{ secrets.BUCKET_NAME_LAB }}/develop/v1/
    - name: Create Github Release
      if: ${{ github.ref == 'refs/heads/master' && env.THIS_VERSION_COMPARABLE > env.LATEST_VERSION_COMPARABLE }}
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: v${{ env.THIS_VERSION }}
        release_name: Release v${{ env.THIS_VERSION }}
        body: |
          See the CHANGELOG for a list of features included in this release
        draft: false
        prerelease: true
    - name: configure PRO AWS credentials
      if: ${{ github.ref == 'refs/heads/master' && env.THIS_VERSION_COMPARABLE > env.LATEST_VERSION_COMPARABLE }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ASSUME_ROLE }}
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_REGION }}
    - name:  Copy to PRO S3
      if: ${{ github.ref == 'refs/heads/master' && env.THIS_VERSION_COMPARABLE > env.LATEST_VERSION_COMPARABLE }}
      run: |
        aws s3 sync ./site/ s3://${{ secrets.BUCKET_NAME }}/
    - name: Invalidate PRO CloudFront cache
      if: ${{ github.ref == 'refs/heads/master' && env.THIS_VERSION_COMPARABLE > env.LATEST_VERSION_COMPARABLE }}
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
